version: 2
jobs:
  setup:
    docker: &docker
      - image: circleci/ruby:2.5.3-node
        environment:
          BUNDLE_PATH: vendor/bundle

    steps:
      - checkout

      - run:
          name: Check if Ruby versions match
          command: test "$(ruby -v | grep -oP '\d\.\d\.\d')" = "$(cat .ruby-version)"

      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "eu_central_bank.gemspec" }}

      - run:
          name: install dependencies
          command: |
            bundle install --jobs=4 --retry=3

      - save_cache:
          key: v1-dependencies-{{ checksum "eu_central_bank.gemspec" }}
          paths:
            - vendor/bundle

  lint:
    docker: *docker

    steps:
      - attach_workspace:
          at: .

      - run: bundle exec rake rubocop

  test:
    docker: *docker
    steps:
      - run:
          name: run tests
          command: |
            mkdir /tmp/test-results

            bundle exec rspec \
              --format progress \
              --format RspecJunitFormatter \
              --out /tmp/test-results/rspec.xml \
              --format progress

      - store_test_results:
          path: /tmp/test-results
